- src/ng-select/ng-select.component.scss
Changed the z-index of ng-outer-menu to 3, so that it remains always visible when opened on top of a .input-group.form-control element.  .input-group .form-control has a z-index of 2 and thus was visible on top of the dropdown
> Z-index for ng-outer-menu

- README.md
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
this allows to expose `isLoading` safely and having a EventEmitter so it can be listened on and changed from outside.
> wrap isLoading in a getter and setter loading

- src/ng-select/ng-select.component.ts
This will set `touched` on closing the option instead of open.
A typical HTML Select in Angular will set touched once the user
mouse clicks out or tabs (keyboard) out. This will emulate that
same behaviour. Setting `touched` right away on open causes
weird user experience when displaying error message that 
typically depend on `touched` being set. We want to let
the user interact with the select and once done interaction,
it is to be set `touched`.
PR Closes #225. A modification to the change in PR #228.
Would greatly appreciate if you can include in this a new version or recut version `0.17.0` with this included this PR is accepted. Awesome job on this great library 👍 
/cc @anjmao
> fix: setTouched on Select Close instead of Open

- src/ng-select/ng-select.component.html
These two functions don't take any arguments, so when using `fullTemplateTypeCheck` with AOT compiler, it will fail because the argument count does not match.
> fix(template): fix AOT compile error

- src/ng-select/ng-dropdown-panel.component.ts
On my side it only fire when scroll equal to clientHeight since I using custom style for ng-select.
> fix(scrollToEnd): fire when scroll equal to clientHeight.

- demo/app/examples/custom-templates.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/ng-select/ng-templates.directive.ts
Providing provision for loading, no data found, type for search state. Closes #217 , #201 
Also adding a demo in templates section for the same on the demo page.
Use `ng-loadingtext-tmp`, `ng-notfound-tmp` and `ng-typetosearch-tmp`
> feat(template): loading, not found, type to search state template options.

- src/themes/default.theme.scss
Resolves #354 by adding `display: inline-block;` to `.ng-value-icon` and `.ng-value-item` of multiple default theme.
> fix: incorrect border on multiple default theme (#354)

- src/ng-select/guid.ts
- src/ng-select/id.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.types.ts
> Adding basic support for Narrators on Dropdown

- demo/app/examples/data-source.component.ts
- src/ng-select/ng-select.component.ts
Fixes and passes tests for the ng-option bug when the ng-option is populated after the ngAfterViewInit has ran.
> Fix for only 1 ng-container that populates after ngAfterViewInit is ran

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
Item list updates result in a reset of the filtered item list. This will result in an inconsistent state in case the ng-select is open while item list updates arrive.
This PR corrects the problem.
> Bugfix: keep filter status consistent with items updates

- src/ng-select/ng-option-highlight.directive.spec.ts
- src/ng-select/ng-option-highlight.directive.ts
> fix: highlight term using typeahead

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
This allows us to dismiss dropdown panel when touching elements outside the selection menu on touch-enabled devices such as phones.
> Listen to `touchstart` events for outside click.

- src/index.ts
- src/ng-select/items-list.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/ng-select/selection-model.ts
> fix: use factory to resolve new instance of selection model

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: don't fire change event for same selection

- README.md
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/ng-select/ng-select.types.ts
Resolves #877 - Adds an `openOnEnter` parameter that defaults to true, and can be set in the global config. This keeps the current functionality while providing a route to enable the more accessible behavior globally.
> Allow form to submit when enter is pressed on a closed ng-select

- package.json
- src/package.json
closes #883
https://www.npmjs.com/package/@ng-select/ng-select should have a link back to github if its working correctly, so I've updated it with a nice short github link that should work.
no link back to github ^
> fix: repository links, silence angular 7 install warning

- src/ng-select/ng-select.component.html
Adding aria-selected attribute on selected items, allow screen readers to tell if an item is selected or not.
> add aria-selected attribute on selected items

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.html
alternative fix for issue #961
Adds the searchTerm to the header and footer template context.
> feat(templates): add searchTerm to header and footer (ng-select#961)

- src/ng-select/ng-dropdown-panel.component.ts
$event.path does not work in Safari and Firefox. Changing that with $event.composedPath() will give it cross-browser support. 
https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath
> [fix] - $event.path does not work in Safari and Firefox. Replace with $event.composedPath().

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
Sometimes with more complex and heavy selects it's possible to glitch the dropdown panel by quickly clicking multiples times on "arrow" - the panel gets appended to body even though it is already closed/destroyed. So it hangs there forever on top of all elements/pages. (This happens only with `appendTo` property).
This happens because this line is not aware of `destroy$`: https://github.com/ng-select/ng-select/blob/97f4387e3e2680e1a4fbf33f76134c44dc31beb6/src/ng-select/ng-dropdown-panel.component.ts#L138
> fix: do not append dropdown, nor update its position when it is destroyed

- src/ng-select/ng-select.component.ts
The `this.open()` in the `filter()` will open the **NgDropdownComponent** and its `_handleItemsChange()` will refresh with the unfiltered data, only after this the **NgSelectComponent** will emit the filtered data to the **NgDropdownComponent**. 
I moved the `this.open()` to after emitting the data so **NgDropdownComponent** can render the filtered data.
> fix: Filter dropdown after selected item with virtualScroll

- src/ng-option-highlight/lib/ng-option-highlight.directive.spec.ts
- src/ng-option-highlight/lib/ng-option-highlight.directive.ts
Contributing to #739, highlighting each instance of the search term
I'm not sure about the expected behavior of special characters, let me know if I need to change anything
> use regex with multiple return to highlight multiple search terms

- src/ng-select/lib/ng-select.component.ts
In angular 7 version footer or header template can be drawn dynamically, but in angular 8, there static properties must be false. 
something like this:
https://stackblitz.com/edit/angular-prsuca-kjjpbt
I don't know If other templates should be dynamic, they are not needed in my case
> dynamic footer and header template

- src/demo/app/examples/append-to-example/append-to-example.component.scss
There was a misspelling in the attribute "width". Looks like it is not necessary.
> fix: styles for "Append to element" example

- src/ng-select/lib/ng-select.component.ts
> fix: make all templates dynamic

- README.md
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
> feat: add readonly attribute

- README.md
- src/demo/app/app.component.ts
- src/ng-select/lib/config.service.ts
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
This PR provides feature as expected in #1276
Provided `appendTo` option globally. 
Also, If `appendTo` property is available in `ng-select` template, then the provided value will be taken as value.
> feat: Append appendTo NgSelectConfig

- README.md
- src/demo/app/app.component.ts
- src/ng-select/lib/config.service.ts
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
This feature has the ability to add `bindValue` as a global config. Also, if needed, one can override bindValue for the specified template by defining `bindValue` as property.
`<ng-select     
bindValue="some-new-value">
</ng-select>`
This closes the #516 feature request.
> feat: bindValue as global config

- src/demo/app/examples/group-selectable-example/group-selectable-example.component.ts
- src/ng-select/lib/items-list.spec.ts
- src/ng-select/lib/selection-model.ts
Disabled items are now unaffected by group selection. The following cases are now covered:
* `selectableGroup=true, groupAsModel=true`
* Select group with no disabled items -> Group selected
* Select group with disabled items -> All non-disabled items are selected
* Select group where all disabled items are selected -> Group selected
* `selectableGroup=true, groupAsModel=false`
* Select group with no disabled items -> All items are selected
* Select group with disabled items -> All non-disabled items are selected
Un-selecting a group will return the list back to the prior state. Disabled items are never affected.
> feat: group selection no longer affects disabled items (#1434)

- CHANGELOG.md
As it seems that new versions have their changelogs on releases page, I have added a link.
> fix!: Add a notice on CHANGELOG.md

- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
When you add a dynamic angular class through [class] it overwrites ng-select. Using static classes (class="test") would not create this issue. Related #1535
> fix: ngClass overwrites 'ng-select' class

- src/ng-select/package.json
The ng-select package does not import any modules from @angular/localize.
Should a library user want to use @angular/localize in their project,
the Angular CLI will ensure they are using consistent @angular/* packages
along the way, thus it's not possible for the user to use a version that
is out of range.
closes ng-select#1576
> chore: remove @angular/localize as peerDependency

- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-select.component.spec.ts
This PR contains 
* **change**:  that updates panel items first div with selector #padding to have height 0px if virtual scroll is disabled.
* **tests**: 2 unit tests covering 2 cases where virtual scroll is enabled/disabled.
The issue link is bellow:
https://github.com/ng-select/ng-select/issues/1708
> fix: fix panel items child height when virtual scroll disabled

- package-lock.json
- src/ng-select/themes/ant.design.theme.scss
I'm using Ant Design Theme ng-select and found that it can't be closed by the arrow button after selected an item. It is found that the css style of the arrow button did not handle well. "pointer-events" is none when opacity is 0, but it did not set back to "auto" when opacity is 1. It is fixed by adding "pointer-events: auto;".
> fix antd style - cant close dropdown with arrow after selected item

- src/ng-select/package.json
Fixes #1717
By adding the `sideEffects` property to this project's `package.json`, angular-cli will respect that and copy it over instead of adding `"sideEffects": false` to the generated `package.json` file.
I tested a build and saw this output in the generated `package.json` file:
```
"sideEffects": [
"*.scss",
"*.css"
],
```
> fix: Explicitly setting the sideEffects property

- src/demo/app/examples/append-to-example/append-to-example.component.html
- src/demo/app/examples/append-to-example/append-to-example.component.scss
- src/demo/app/examples/append-to-example/append-to-example.component.ts
- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-select.component.spec.ts
**Problem**
When the body has full height and we use `appendTo="body"`, when opening the select dropdown, the dropdown menu is being misplaced.
This issue can be demonstrated at https://stackblitz.com/edit/ng-select-position-issue
**Cause**
When appending the dropdown menu to another container, we are waiting for the dom element to be inserted before calculating the left offset. Problem with this is after appending the menu, it could have triggered the scrollbar to appear, and our left offset is calculated based on when scrollbar is shown. And after we re-positioned the menu, the scrollbar disappears and we end up with misaligned menu.
**Fix**
Separated updates to the horizontal and vertical offset, so that we calculate the left offset before appending the menu, and calculate the vertical …
> fix: fix menu position when scrollbar is not visible (#1404)

- README.md
- Fix example with `items` binding
- Fix link to the demo page
Related to #1753
> fix(doc): fix basic example bindings

- src/demo/app/examples/append-to-example/append-to-example.component.html
- src/demo/app/examples/append-to-example/append-to-example.component.scss
- src/demo/app/examples/append-to-example/append-to-example.component.ts
Previous example looks bad when we start to make selections.
Now simplified it to just demonstrate appending to a parent div.
Related to #1739
> fix: simplify append to example

- src/ng-select/lib/ng-dropdown-panel.component.ts
On Internet Explorer 11 the `path` is undefined
Closes: #1780
> fix: make _handleScroll function compatible with ie11

- src/ng-select/lib/ng-select.component.ts
When using in not searchable mode (dropdown)  you can press keys and ng-select will mark the option that starts from that key, but right now if that option is in scroll, it won't scroll to it. This PR fixes it by adding
```js
this._scrollToMarked();
```
right after
```js
this.itemsList.markItem(item);
```
Before:
After:
> fix: scroll to marked item while not searchable

- src/ng-select/lib/items-list.ts
- src/ng-select/lib/ng-select.component.spec.ts
#1628
While filtering, the item received by `this._groups.get(key)`  had the old "selected" property (and maybe all others too) since all of them were not updating after selecting another item
> fix: "selected" property of values inside groups map with undefined key is not updating correctly when the original property change 

- src/ng-select/lib/ng-select.component.ts
There are 2 reasons to allow setting compareWith to null/undefined.
1. Reverting the set compareWith - possible the user of the ng-select might want to remove the previously set compareWith to allow default behaviour in combination with bindValue possibly.
2. Extensibility - we have a wrapper around the ng-select that provides custom styles, adds error messages. Not all use cases use compareWith, but some do. Now it is impossible to redirect the [compareWith] @Input without setting the default. That hinders the bindValue default behaviour.
> feat: Allow nullish compareWith

- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
When using the async pipe and angulars strict template checking this will no longer throw.
fixes Ref#1580
fixes Ref#1581
> feat: allow items to be null

- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/selection-model.ts
It's a weird case, but when you set up page zoom in browser eg 67%, scrollToEnd does not fire because of non-integer pixels:
scrollTop 319.5 + this._dropdown.clientHeight 240 >= padding.clientHieght 560 // false
> fix: add 1 pixel for reliable triggering scrollToEnd

- src/ng-select/lib/ng-dropdown-panel.component.ts
This PR reduces change detection cycles for the `ng-dropdown-panel` by replacing
`HostListener` with `fromEvent` outside of the zone. Calling `preventDefault()`
on the event doesn't require Angular to run `ApplicationRef.tick()`. Note that the
`HostListener` wraps the actual listener under the hood into the internal Angular function
which runs `markDirty()` before running the actual listener (the decorated class method).
> perf: reduce change detection cycles  by listening the `mousedown` in the root zone

- src/ng-select/lib/config.service.ts
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
This PR adds a way to define a default `clearSearchOnAdd` in NgSelectConfig as described in #1973 , but can be override if user define `[clearSearchOnAdd]` on the component.
> feat: add clearSearchOnAdd to NgSelectConfig

- src/demo/app/examples/dropdown-position-example/dropdown-position-example.component.html
- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-select.component.ts
- src/ng-select/themes/ant.design.theme.scss
- src/ng-select/themes/default.theme.scss
- src/ng-select/themes/material.theme.scss
Adds the ability to set `dropdownPosition` to `'left'` or `'right'` as described in #1060.
- The position `'auto'` can still only set the `dropdownPosition` to `'top'` or `'bottom'`.  
I am not sure how to automatically determine whether to use `'left'` or `'right'` or whether it is a good idea.
- Appropriate styling has been added for all three themes.
- Additional examples have been added to the demo's dropdown-position page.
> feat: add 'left' and 'right' options to dropdownPosition

- src/ng-select/package.json
This fixes an issue with v8.x that was missed in #1996 
See: https://angular.io/guide/creating-libraries#managing-assets-in-a-library
> fix: fix scss files not being exported for Angular 13

- package.json
Angular build flag `--prod` is deprecated. Updates package.json to use `--configuration production` instead.
> chore: update deprecated build --prod flag

- .github/workflows/ci.yml
- .github/workflows/release.yml
Angular 14 does not support Node 12 or below. This commit updates Github actions to use Node version 14
> feat(cicd): updates GitHub actions node version to 14

- src/ng-select/package.json
My application was having trouble importing the ng-select themes into less after an update to Angular 14. We found that the files needed to be exported in the package.json so they could be found by the builder. This is backpacking off a similar commit recently that exported the .scss files, but missed exporting the .css files.
> Add css exports to package.json

- src/ng-select/lib/ng-select.component.ts
This prevents safari 16.0 from jumping to the top as it seems Safari 16.0 doesn't like setting focus on a readonly element
> fix: setting focus to input element only if its not readonly, fixes 2133

- .github/workflows/release.yml
This change updates the release workflow to use `yarn` as that's the package manager this repository uses
> build: use yarn in release workflow instead of npm

- .github/workflows/release.yml
This change updates the release workflow to set the registry URL which generates a config which allows the NODE_AUTH_TOKEN environmental variable to be used, enables caching, and provides the NODE_AUTH_TOKEN to only the publish step of the release workflow.
> build: update release.yml

- README.md
- src/ng-select/lib/config.service.ts
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
This feature enables deselecting an option from the dropdown when `multiple` is `false`. The user can
click on a selected option, which will deselect that option instead of closing the dropdown.
Fixes #2053
> feat: deselect option from dropdown in single select

- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
- src/ng-select/testing/helpers.ts
- src/ng-select/themes/ant.design.theme.scss
- src/ng-select/themes/default.theme.scss
- src/ng-select/themes/material.theme.scss
Addresses the issue https://github.com/ng-select/ng-select/issues/2239
> Add Clear Button keyboard accessibility

- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
A potential solution for the following issue: #2288
> fix(ng-option): Remove event emits full ng-select model instead of direct value

- README.md
- src/ng-select/lib/ng-select.component.ts
As noted in the README `isOpen` is not required. This change is necessary for library consumers activating strict type checking in angular templates, otherwise we need to strictly pass a boolean and there is no possibility to switch to and from automatically open/close to manually open/close.
> fix(ng-select): isOpen is optional as noted in the README

- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-option.component.ts
- src/ng-select/lib/ng-select.component.ts
adding to ng-dropdown-panel, ng-option and ng-select
> feat: add boolean and number transformers

- README.md
- src/ng-option-highlight/lib/ng-option-highlight.directive.spec.ts
- src/ng-option-highlight/lib/ng-option-highlight.directive.ts
- src/ng-option-highlight/lib/ng-option-highlight.module.ts
- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-option.component.ts
- src/ng-select/lib/ng-select.component.ts
- src/ng-select/lib/ng-select.module.ts
- src/ng-select/lib/ng-templates.directive.ts
Migration to standalone components. Closes #2392
It is backwards compatible: `NgSelectModule`, that exports all components and directives, can be imported as before
But now components and directives can be imported one by one as well
Sub PRs to make review easier, to be merged before merging this one
* https://github.com/pkurcx/ng-select/pull/1
* https://github.com/pkurcx/ng-select/pull/2
> Migrate to standalone components

- src/ng-select/lib/ng-select.component.ts
Fixed this issue: https://github.com/ng-select/ng-select/issues/2399
Dropdown position recalculation was missing for some cases which I described in issue I've created earlier, please see:https://github.com/ng-select/ng-select/issues/2399
> fix: triggers dropdown position recalculation on select/deselect (#2399)

- README.md
In 'README.md' the API description for 'bufferAmount' is incorrect.
> Fix API Description for 'bufferAmount'

- src/ng-select/lib/ng-select.component.scss
- src/ng-select/lib/ng-select.component.ts
Currently, when `ng-select` is disabled, you cannot select the label of a selected item (e.g. by double-clicking). 
In contrast, a standard disabled `<input>` still allows text selection.
Allowing text selection is useful when building read-only (disabled) forms, 
as it lets users copy selected values for reuse.
Fixes #2107.
> fix: allow text selection when ng-select is disabled
