ng-select/ng-select

- src/lib/src/items-list.ts
- src/lib/src/ng-select.component.ts
- src/lib/src/ng-select.types.ts
- ability to clear filter with backspace key (single & multiple);
- ability to clear filter during typing with cross button.
> clear improvements: backspace management & filter clear

- README.md
- src/lib/src/items-list.ts
- src/lib/src/ng-select.component.html
- src/lib/src/ng-select.component.scss
- src/lib/src/ng-select.component.spec.ts
- src/lib/src/ng-select.component.ts
- src/lib/src/ng-select.types.ts
- src/lib/src/virtual-scroll.component.spec.ts
- src/lib/src/virtual-scroll.component.ts
> fix: Virtual scroll scrollTop value calculation

- src/demo/app/examples/autocomplete.component.ts
- src/lib/src/items-list.ts
- src/lib/src/ng-select.component.spec.ts
- src/lib/src/ng-select.component.ts
> fix: clear filter value on selected item

- src/demo/app/layout/header.component.ts
- src/lib/src/ng-select.component.html
- src/lib/src/ng-select.component.scss
- src/lib/src/ng-select.component.spec.ts
- src/lib/src/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/81
> fix: add typeahead css class binding on host

- demo/app/examples/reactive-forms.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.ts
> fix: focus filter on clear

- src/ng-select/ng-select.module.ts
This will leave users to choose between `FormsModule` or `ReactiveFormsModule`.
> feat: remove unnecessary FormsModule.

- README.md
- demo/app/examples/reactive-forms.component.ts
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat(sarchable): allow to toggle searchable

- src/ng-select/ng-select.component.scss
fixes https://github.com/ng-select/ng-select/issues/118
> fix: do not wrap text in ng-option

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix(events): don't fire change event on search clear

- demo/app/examples/multi.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat: support for simple arrays

- demo/app/app.component.ts
- demo/app/examples/bindings.component.ts
- demo/app/examples/custom-templates.component.ts
- demo/app/examples/events.component.ts
- demo/app/examples/multi.component.ts
- demo/app/examples/reactive-forms.component.ts
- demo/app/examples/search.component.ts
- demo/app/examples/tags.component.ts
- demo/app/examples/virtual-scroll.component.ts
- src/ng-select/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/138
> fix: mark for check when closing dropdown

- README.md
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat: allow to configure marking first item

- README.md
- demo/app/examples/events.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
https://github.com/ng-select/ng-select/issues/149
> feat: add add, remove, clear events

- README.md
- demo/app/app.module.ts
- demo/app/examples/dropdown-positions.component.ts
- demo/app/layout/sidenav-component.ts
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat: Allow to change dropdown positioning.

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
> fix: check if bindLabel exist while searching for selected items

- src/ng-select/ng-select.component.scss
fixes https://github.com/ng-select/ng-select/issues/183
> fix: make ng-input z-index bigger to focus on placeholder click

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: add missing types

- README.md
- demo/app/examples/custom-templates.component.ts
- demo/app/examples/reactive-forms.component.ts
- demo/app/shared/data.service.ts
- demo/style/_content.scss
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/ng-select/ng-templates.directive.ts
closes https://github.com/ng-select/ng-select/issues/184
> Header footer templates

- demo/app/app.module.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/virtual-scroll.component.ts
Solves problems in #146 
1. Not able to add tag if there are items matching search term
2. Selected items are visible among options even if they don't match search term
> Tag improvements

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: check if value is defined

- README.md
- demo/app/examples/multi.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/virtual-scroll.component.spec.ts
- src/ng-select/virtual-scroll.component.ts
https://github.com/ng-select/ng-select/issues/222
> Close dropdown on select by default

- src/ng-select/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/225
> add touched on dropdown open

- demo/app/examples/bindings.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
https://github.com/ng-select/ng-select/issues/219
> feat: add support for nested bindings

- src/ng-select/ng-select.component.html
> fix: Not found text is not used for custom tags #234

- demo/app/examples/custom-templates.component.ts
- demo/app/examples/reactive-forms.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-option-highlight.directive.spec.ts
- src/ng-select/ng-option-highlight.directive.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.module.ts
- src/ng-select/ng-select.types.ts
https://github.com/ng-select/ng-select/issues/152
highlight search term in the items with a default style 'hightlight' (bold and underline text)
> feat: highlight search term in labels in dropdown list

- README.md
- demo/app/examples/dropdown-positions.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat: determine dropdownPosition automatically

- src/ng-select/ng-select.component.ts
> focus only if filter value is not set

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: don't show not found text while loading

- README.md
- demo/app/examples/tags.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat(tags): support promise while creating new tag

- src/ng-select/items-list.ts
- src/ng-select/ng-option-highlight.directive.ts
- src/ng-select/ng-select.component.spec.ts
> fix: mark first item when selected is not among options

- demo/app/examples/data-source.component.ts
- src/ng-select/ng-option-highlight.directive.ts
- src/ng-select/ng-option.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat(ng-option): support for disabled attribute

- demo/app/examples/reactive-forms.component.ts
> Renames Model/model to Modal/modal in Reactive Form demo

- src/ng-select/ng-dropdown-panel.component.ts
fixes https://github.com/ng-select/ng-select/issues/303
> remove uneeded node removal logic

- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/themes/material.theme.scss
fixes https://github.com/ng-select/ng-select/issues/297
> fix placeholder

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix(tag): tag should be same type as items

- README.md
- demo/app/examples/groups.component.ts
- demo/app/examples/reactive-forms.component.ts
- demo/app/examples/search.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/utils.ts
- src/themes/default.theme.scss
- src/themes/material.theme.scss
> Selectable group

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
> fix: label formatting

- src/ng-select/console.service.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/testing/mocks.ts
https://github.com/ng-select/ng-select/issues/348
> fix: skip writeValue handling if value is empty

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
> fix: don't mark disabled while opening

- README.md
- demo/app/examples/groups.component.ts
- integration_test.sh
- package.json
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- tslint.json
https://github.com/ng-select/ng-select/issues/375
> allow group by expression

- README.md
- demo/app/examples/dropdown-positions.component.ts
- src/ng-select/ng-dropdown-panel.component.scss
- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/themes/default.theme.scss
#367 #256 https://github.com/ng-select/ng-select/issues/306
> Auto position dropdown

- README.md
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
https://github.com/ng-select/ng-select/issues/370
> allow to select on tab

- README.md
- demo/app/examples/search.component.ts
- package.json
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- yarn.lock
https://github.com/ng-select/ng-select/issues/387 and https://github.com/ng-select/ng-select/issues/167
> feat: searchFn support for multiple fields

- demo/app/examples/search.component.ts
- release.sh
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/405
> Fix type to search

- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/368
> Input focus fix

- demo/app/examples/tags.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix(hideSelected): allow to open dropdown when tagging enabled

- package.json
- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/window.service.ts
- src/testing/mocks.ts
- yarn.lock
> fix: close dropdown on outside click

- demo/app/examples/search.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/399
> fix: do not try to set loading state automatically

- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.ts
> feat: transfer classes to dropdown-panel

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/testing/helpers.ts
> feat: support item navigation while not searchable

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: keep input focused while clicking inside dropdown

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: reset marked item when items updated

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: emit event while removing using backspace

- demo/app/app.module.ts
- demo/app/examples/groups.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.types.ts
- src/themes/default.theme.scss
- src/themes/material.theme.scss
> fix(typeahead): don't insert option back to list for newly created tag

- README.md
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
> fix: allow to use compareWith fn when bindValue is used

- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
fixes https://github.com/ng-select/ng-select/issues/599
> fix: use [attr.id] instead of [id]

- demo/app/examples/multi.component.ts
Example with limit is using model from another example, which means that one example is being affected by other.
> Update multi.component.ts - fix example with limit

- README.md
- demo/app/examples/tags.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> Control open

- demo/app/examples/groups.component.ts
- demo/app/shared/data.service.ts
- src/ng-select/items-list.spec.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.types.ts
- src/ng-select/selection-model.ts
- src/ng-select/value-utils.ts
fixes https://github.com/ng-select/ng-select/issues/606
> Fix grouped items select/unselect

- src/ng-select/items-list.spec.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: don't ignore bindLabel when label prop exists

- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/themes/default.theme.scss
> fix: increase arrow click area

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: focus select after unselecting single item

- src/ng-select/items-list.spec.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix(tagging): don't show tag if it exists among items or selected

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix: allow to reposition input cursor using mouse

- demo/app/examples/tags.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/ng-select/ng-templates.directive.ts
> feat: addTag custom template

- package.json
Add the git URL. This will display the URL on the npm package website
> docs(package): add repository

- README.md
- demo/app/examples/events.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat: emit search event

- demo/app/examples/groups.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/themes/default.theme.scss
- src/themes/material.theme.scss
Cherry-picked commits from master
> Fixed grouping items without keys in v1.x

- demo/app/app.component.html
- demo/app/app.component.ts
- demo/app/layout/header.component.ts
- src/themes/_mixins.scss
- src/themes/default.theme.scss
- src/themes/material.theme.scss
This pr adds [RTL support feature](https://github.com/ng-select/ng-select/issues/426)
> RTL support

- src/ng-select/items-list.spec.ts
- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
> issue(#729) Fix dropdown select when used in web component

- src/ng-select/ng-option-highlight.directive.spec.ts
- src/ng-select/ng-option-highlight.directive.ts
fixes #591
Cherry-picked commit that fixed it for Angular v6.x
> Fix: highlight term using typeahead

- demo/app/examples/virtual-scroll.component.ts
- src/ng-select/items-list.spec.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.scss
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.types.ts
- src/themes/default.theme.scss
- src/themes/material.theme.scss
> Fixes & improvements

- src/ng-select/ng-select.component.ts
> fix: handler mousedown for clear event when used animation library

- demo/app/app.component.ts
- demo/app/examples/reactive-forms.component.ts
- src/ng-select/config.service.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.types.ts
> fix: map selected items while source changed

- src/ng-select/ng-dropdown-panel.component.ts
> fix: appended dropdown position

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
> fix: keep selected items while bindValue is incorrect

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.ts
> Removed EventEmitter generic type from scrollToEnd

- README.md
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.ts
> Added autocorrect and autocapitalize inputs

- demo/app/examples/groups.component.ts
- package.json
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- yarn.lock
Closes https://github.com/ng-select/ng-select/issues/186
> Initial children grouping implementation

- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> fix(ng-option): don't filter out empty array

- demo/app/examples/multi.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/selection-model.ts
> fix: don't allow to unselect disabled items

- demo/app/examples/multi.component.ts
- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/selection-model.ts
- src/themes/default.theme.scss
> fix: remove disabled items while setting new model

- src/themes/material.theme.scss
Hi!
I were using your package on a project with IE compatibility so I fixed (I think 😃) few mistakes on the material theme.
Before
After
> fix(material): material theme input container

- README.md
- demo/app/examples/events.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
> feat: expose filtered items through search event

- src/ng-select/ng-dropdown-panel.component.ts
Wrapping the call to `_currentPosition` in a setTimeout so the dropdown has fully rendered before we check the size.
> Fix for #1042

- demo/app/examples/custom-templates.component.ts
- src/ng-select/ng-select.component.html
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
- src/ng-select/ng-select.module.ts
- src/ng-select/ng-templates.directive.ts
Add custom loading spinner template using ` <ng-template ng-loadingspinner-tmp></ng-template>`
Fix request #1109
> feat: Add template for custom loading spinner

- src/ng-select/items-list.ts
> fix(hideSelected): allow in single selection

- src/ng-select/ng-dropdown-panel.component.ts
- src/ng-select/ng-select.component.spec.ts
- src/ng-select/ng-select.component.ts
this feature is related on issue #1149 
In this PR a added getter for current dropdown panel position
> feat: add getter for current dropdown position

- src/themes/default.theme.scss
Follow on from #388.  Creates additional variables for further customization without overriding styles.
> exposing additional sass variables

- src/ng-select/ng-dropdown-panel.component.ts
> fix: adjust dropdown position on selection change - include top

- src/ng-select/items-list.ts
- src/ng-select/ng-select.component.ts
use dropdownId with index as option htmlId
fixes #1244
fixes #1181
fixes #1218
fixes #1229
> fix: track by htmlId by default

- src/ng-select/items-list.spec.ts
- src/ng-select/items-list.ts
> fix: mark first item when last marked is filtered out

- src/demo/app/examples/forms-with-options-example/forms-with-options-example.component.html
- src/ng-select/lib/ng-option.component.ts
- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
- src/ng-select/lib/ng-select.module.ts
- src/ng-select/lib/ng-templates.directive.ts
- src/ng-select/lib/value-utils.ts
> fix(ng-option): handle label updates

- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
> fix: emit typeahead value when search is cleared after item is added

- src/ng-select/public-api.ts
> feat: expose DropdownPosition type

- README.md
- src/ng-select/lib/config.service.ts
- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.ts
- src/ng-select/themes/material.theme.scss
Discussion: https://github.com/ng-select/ng-select/issues/1334
> feat: add appearance property for material theme

- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
> fix: emit empty string for default term length

- src/ng-select/lib/ng-select.component.scss
- src/ng-select/themes/ant.design.theme.scss
- src/ng-select/themes/default.theme.scss
- src/ng-select/themes/material.theme.scss
> fix(style): fixed color in base styles

- .github/workflows/release.yml
> chore: add gh-pages deployment

- src/ng-select/lib/ng-select.component.spec.ts
> fix: tests

- src/ng-select/themes/material.theme.scss
> fix: appearance outline cut off

- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-select.component.ts
- yarn.lock
fix `appendTo` validation closes #1539
improve `bindValue` warning closes #1639, closes #1640
> fix: small improvements

- src/demo/app/examples/append-to-example/append-to-example.component.scss
- src/demo/app/examples/append-to-example/append-to-example.component.ts
- src/ng-select/lib/ng-dropdown-panel.component.ts
> fix: use composePath while handling scroll

- README.md
This PR for #1753. Added small basic examples of usage ng-select to readme file
> chore(doc): add basic examples to readme

- src/ng-option-highlight/package.json
> chore: bump ng-option-highlight to angular 10

- src/ng-select/lib/items-list.spec.ts
- src/ng-select/lib/items-list.ts
I changed the way of  _getNextItemIndex is working because in some cases the value for markedIndex was wrong.
> fix: Issue when using hideSelected =true and closeOnSelect=false

- src/ng-select/lib/ng-select.component.html
> fix:label template is ignored when multi label template is defined 

- src/ng-select/lib/config.service.ts
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
This adds support for the new config.bindLabel property, requested in #1751
> feat: support bindLabel in global config

- README.md
docs: Update Readme file with v 6.0 (Angular 11)
> docs: Update Readme file with v 6.0 (Angular 11) [skip ci]

- .github/workflows/ci.yml
- angular.json
- package.json
- src/demo/assets/stackblitz/polyfills.ts
- src/demo/environments/environment.ts
- src/demo/polyfills.ts
- src/ng-option-highlight/package.json
- src/ng-option-highlight/test.ts
- src/ng-select/package.json
- src/ng-select/test.ts
- yarn.lock
> feat: upgrade to angular 12

- README.md
- src/ng-select/package.json
Missed updating the README and package.json in #1903
Resolves #1918
> fix: update peer dep declaration ng 12

- package.json
- src/ng-select/package.json
Change the engine versions of npm and node for recommended in angular 12
> feat: recommended engines versions for angular 12

- src/ng-select/themes/default.theme.scss
- Updated `$ng-select-border-radius` variable support
- Added more default scss variables for better flexibility
> feat: add more default scss variables for better flexibility

- angular.json
> fix(docs): fixes a bug that does not display docs

- package.json
- src/demo/app/app.module.ts
- src/ng-option-highlight/lib/ng-option-highlight.directive.spec.ts
- src/ng-option-highlight/lib/ng-option-highlight.directive.ts
- src/ng-option-highlight/lib/ng-option-highlight.module.ts
- src/ng-option-highlight/test.ts
- src/ng-option-highlight/tsconfig.lib.json
- src/ng-select/lib/ng-dropdown-panel.component.ts
- src/ng-select/lib/ng-option.component.ts
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
- src/ng-select/lib/ng-select.module.ts
- src/ng-select/package.json
- src/ng-select/test.ts
- src/ng-select/tsconfig.lib.json
- tsconfig.json
- yarn.lock
BREAKING CHANGE: adds angular 15 support
> feat(core): adds angular 15 support

- src/demo/assets/stackblitz/polyfills.ts
> fix: stackblitz examples

- src/ng-select/lib/ng-select.component.ts
> fix: revert `isOpen` flag

- README.md
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
As requested in https://github.com/ng-select/ng-select/issues/948. 
Added new flag that will control prevent right mouse click option
> feat: prevent toggle on right mouse click

- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.ts
> fix: fixes incorrect styling of ng-class

- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
> feat: adds `aria-label` for input

- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.spec.ts
- src/ng-select/lib/ng-select.component.ts
> feat: adds dropdown panel aria label `ariaLabelDropdown` support

- src/ng-select/lib/ng-select.component.html
> fix(accessibility): placeholder announced by SRs

- src/ng-select/lib/ng-select.component.html
> fix: Remove role listbox on ng-dropdown-panel

- src/ng-select/lib/ng-dropdown-panel.component.ts
appendTo does currently not work within the shadowRoot. I have made sight adjustments to enable this functionality
> fix: appendTo for shadow dom

- src/ng-select/lib/ng-select.component.html
- src/ng-select/lib/ng-select.component.ts
> feat(ng-select): update items when groupBy changes without items
